server:
  port: 9200
spring:
  profiles:
    active: dev
  application:
    name: diana-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iblog_data?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root123
